# Note: once the event has started:
# change all four occurrances of PRIMARY BUTTON LINK
baseURL = "https://makezurich.ch/"
title = "Make Zurich"
theme = "hugo-hackatheme"
languageCode = "en-us"
defaultContentLanguage = "en"
#disableLanguages = ["de"]
enableMissingTranslationPlaceholders = false    # If you're adding a new translation languange, you might want to set the following to true

[params]
dateStart = 2023-06-02T18:00:00+02:00           # Required
dateEnd = 2023-06-10T22:00:00+02:00             # Required
dateForm = "January 2, 2006"                    # Required, defines date formatting style (see Hugo dateFormat)
hashtag = "MakeZurich"

[params.license]                                # Optional, but highly recommended
name = "CC-BY-SA 4.0"
url = "https://github.com/make-zurich/website/blob/master/LICENSE"

[params.styling]
backgroundHero = "/images/front/background.jpg"           # Required
logoHero = "/images/logo/logo-inv-2023.png"                   # Required
logoNavbar = "/images/logo/logo.svg"                     # Optional, leave empty to show no logo on navbar
externalImage = "/images/externals/event-cover.png" # Optional, used for sharing meta data
themeColor = "#ffffff"                              # Optional
customCSS = "/css/styles.css"                       # Optional, remove/leave empty if you don't need custom styles

# Venue description
# Details are used to generate maps and schema.org meta-data
[params.venue]
name = "TBD"
street = "-"
zipCode = "8005"
city = "Z端rich"
state = "Z端rich"
country = "Switzerland"
mapboxPublicToken = "pk.eyJ1IjoiZ29uemFsb2Nhc2FzIiwiYSI6ImNpa2JnMDI2cDAwMzR3bGx2eXkyZDh4a3QifQ.sgne64JeXpvQee49WW1oTA"
mapboxStyle = "light-v10"
mapboxZoom = 15

[params.venue.coords]
latitude = 47.3875968
longitude = 8.5207705

# Registration
[params.registration]
registrationForm = "#soon"

# Organizers of the event: add as many as you need.
[[params.organizers]]
name = "Stadt Z端rich"
logo = "/images/partners/logo-zurich.png"
url = "https://www.stadt-zuerich.ch"

[[params.organizers]]
name = "Open Network Infrastructure Association"
logo = "/images/partners/logo-onia.png"
url = "https://opennetworkinfrastructure.org"

# Team
[params.team]
order = "random"                                # Optional, to maintain the ordering as specified, remove or set to "fixed"

[[params.team.members]]
name = "Francesca Sanfilippo"
photo = "/images/team/francesca.png"

[[params.team.members]]
name = "Gonzalo Casas"
photo = "/images/team/gnz.png"

[[params.team.members]]
name = "Marcus Cathomen"
photo = "/images/team/marcus.png"

[[params.team.members]]
name = "Baxter Yazbek"
photo = "/images/team/baxter.png"

[[params.team.members]]
name = "Oleg Lavrovsky"
photo = "/images/team/oleg.png"

[[params.TBC.team.members]]
name = "Simon Maurer"
photo = "/images/team/simon.png"

[[params.TBC.team.members]]
name = "Michel Racic"
photo = "/images/team/michel.png"

[[params.TBC.team.members]]
name = "Tillo Bosshart"
photo = "/images/team/tillo.png"

[[params.TBC.team.members]]
name = "Dirk Zugenmaier"
photo = "/images/team/dirk.png"

[[params.TBC.team.members]]
name = "Diego Sandoval"
photo = "/images/team/diego.png"

[[params.TBC.team.members]]
name = "Yannick Weiss"
photo = "/images/team/yannick.png"

[[params.TBC.team.members]]
name = "Urs Marti"
photo = "/images/team/urs.png"

[[params.TBC.team.members]]
name = "Alexandra Collm"
photo = "/images/team/alexandra.png"

[[params.TBC.team.members]]
name = "Sandra Veiga"
photo = "/images/team/sandra.png"

[[params.TBC.team.members]]
name = "Juerg Wyser"
photo = "/images/team/juerg.png"

[[params.TBC.team.members]]
name = "Manuel Di Cerbo"
photo = "/images/team/manuel.png"

[[params.TBC.team.members]]
name = "Marco Foco"
photo = "/images/team/marco.png"

[[params.TBC.team.members]]
name = "Raphael Rotondari"
photo = "/images/team/raphael.png"

[[params.TBC.team.members]]
name = "Tiago Neves"
photo = "/images/team/tiago.png"

[[params.TBC.team.members]]
name = "Roxana Pedano"
photo = "/images/team/roxy.png"

[[params.TBC.team.members]]
name = "Cinzia Casotti"
photo = "/images/team/cinzia.png"

# Sponsors of the event
[[params.partners.sponsors]]
name = "Stadt Zurich"
logo = "/images/partners/logo-stez.png"
url = "https://www.stadt-zuerich.ch/prd/de/index/stadtentwicklung.html"
class = "my-3 w-50"

[[params.partners.sponsors]]
name = "EWZ"
logo = "/images/partners/logo-ewz.png"
url = "https://www.ewz.ch"
class = "my-2 w-50"

[[params.partners.sponsors]]
name = "Semtech"
logo = "/images/partners/logo-semtech.png"
url = "https://www.semtech.com"
class = "my-1 w-50"

[[params.partners.sponsors]]
name = "u-blox"
logo = "/images/partners/logo-u-blox.png"
url = "https://www.u-blox.ch"
class = "my-3 w-50"

[[params.partners.sponsors]]
name = "Helium"
logo = "/images/partners/logo-helium.png"
url = "https://www.helium.com/"
class = "my-2 w-50"

[[params.partners.sponsors]]
name = "Miromico GmbH"
logo = "/images/partners/logo-miromico.png"
url = "https://miromico.ch/"
class = "my-2 w-50"

[[params.partners.sponsors]]
name = "SWITCH.CH"
logo = "/images/partners/logo-switch.png"
url = "https://switch.ch/"
class = "my-3 w-50"

[[params.partners.sponsors]]
name = "Sensirion"
logo = "/images/partners/logo-sensirion.png"
url = "https://www.sensirion.com/en/"
class = "my-4 w-50"

[[params.partners.sponsors]]
name = "Brudi GmbH + Co-Co-Co"
logo = "/images/partners/logo-brudi-cococo.png"
url = "https://co-co-co.org/brudi_co-co-co.html"
class = "my-4 w-50"

[[params.partners.sponsors]]
name = "Logiscool Ltd"
logo = "/images/partners/logo-logiscool.png"
url = "https://www.logiscool.com/ch-en/school/zurich"
class = "my-3 w-50"

[[params.partners.sponsors]]
name = "Decentlab"
logo = "/images/partners/logo-decentlab.png"
url = "https://www.decentlab.com/"
class = "my-4 w-50"

[[params.partners.sponsors]]
name = "Netcetera"
logo = "/images/partners/logo-netcetera.png"
url = "https://www.netcetera.com/"
class = "my-2 w-50"

[[params.partners.sponsors]]
name = "Hexagon - Leica Geosystems"
logo = "/images/partners/logo-hexagon-leica.png"
url = "https://leica-geosystems.com/about-us/careers/job-openings"
class = "my-2 w-50"

[[params.partners.sponsors]]
name = "swissdevjobs.ch"
logo = "/images/partners/logo-swissdevjobs.png"
url = "https://swissdevjobs.ch/jobs/All/Zurich"
class = "my-3 w-50"

[[params.partners.sponsors]]
name = "PRiOT"
logo = "/images/partners/logo-priot.png"
url = "https://priot.ch/"
class = "my-3 w-50"

[[params.partners.sponsors]]
name = "Data Center Light"
logo = "/images/partners/logo-datacenterlight.png"
url = "https://datacenterlight.ch/"
class = "my-3 w-50"

[[params.partners.sponsors]]
name = "Rockstar Recruiting"
logo = "/images/partners/logo-rockstar.png"
url = "http://www.rockstar.jobs/"
class = "my-3 w-50"

[[params.partners.sponsors]]
name = "Eden Senses"
logo = "/images/partners/logo-eden.png"
url = "https://www.eden-senses.com/"
class = "my-3 w-50"

[[params.partners.sponsors]]
name = "Digital Republic"
logo = "/images/partners/logo-dr.png"
url = "https://digitalrepublic.ch/"
class = "my-2 w-50"

# Community partners of the event
[[params.partners.community]]
name = "The Things Network"
logo = "/images/partners/logo-ttn.png"
url = "https://www.thethingsnetwork.org/"
class = "my-2 w-50"

[[params.partners.community]]
name = "IoT Zurich"
logo = "/images/partners/logo-iotzh.png"
url = "https://www.meetup.com/IoT-Zurich"
class = "my-4 w-50"

[[params.partners.community]]
name = "opendata.ch"
logo = "/images/partners/logo-opendatach.png"
url = "http://make.opendata.ch/"
class = "my-3 w-50"

[[params.partners.community]]
name = "SGMK"
logo = "/images/partners/logo-sgmk.png"
url = "https://www.mechatronicart.ch/"
class = "my-3 h-50"

[[params.partners.community]]
name = "FabLab Z端rich"
logo = "/images/partners/logo-fablab-zh.png"
url = "https://zurich.fablab.ch/"
class = "my-3 w-50"

[[params.partners.community]]
name = "Prototype Fund CH"
logo = "/images/partners/logo-prototypefund.png"
url = "https://prototypefund.opendata.ch/"
class = "my-2 w-50"

[[params.partners.community]]
name = "Echtzeit Digitale Kultur"
logo = "/images/partners/logo-echtzeit-digitalekultur.png"
url = "https://demonights.ch/"
class = "my-2 w-50"

[[params.partners.community]]
name = "Make.Human.Technology"
logo = "/images/partners/logo-makehumantechnology.png"
url = "https://makehumantechnology.org/"
class = "my-3 w-50"

# [[params.partners.community]]
# name = "Women++"
# logo = "/images/partners/logo-womenplusplus.png"
# url = "https://www.womenplusplus.ch/"
# class = "my-3 w-50"

# [[params.partners.community]]
# name = "GDG Zurich"
# logo = "/images/partners/logo-gdg.png"
# url = "http://www.gdgzh.ch/"
# class = "my-3 w-50"

# [[params.partners.community]]
# name = "Women Techmakers Switzerland"
# logo = "/images/partners/logo-wtm.png"
# url = "https://www.meetup.com/wtm-switzerland/"
# class = "my-3 w-25"

# [[params.partners.community]]
# name = "SWITCH.CH"
# logo = "/images/partners/logo-switch.png"
# url = "https://www.switch.ch/"
# class = "my-4 w-50"

# Challenges: add heading images, url and key
# and then add localizations according that key
[[params.challenges]]
image = "/images/challenges/granny.png"
# url = "/box/1"
i18n = "saw"

[[params.challenges]]
image = "/images/challenges/move-chill.png"
# url = "/box/2"
i18n = "taz1"

[[params.challenges]]
image = "/images/challenges/breathe.png"
# url = "/box/3"
i18n = "ttn"

[[params.challenges]]
image = "/images/challenges/bicycle-parking.png"
# url = "/box/4"
i18n = "taz2"

[[params.challenges]]
image = "/images/challenges/green-spaces.png"
# url = "/box/5"
i18n = "gsz2"

[[params.challenges]]
image = "/images/challenges/transformer-station.png"
# url = "/box/6"
i18n = "ewz"

[[params.challenges]]
image = "/images/challenges/open.png"
# url = "/box/7"
i18n = "open"

[[params.features]]
name = "learning"
background = "/images/features/learning.jpg"

[[params.features]]
name = "hardware"
background = "/images/features/badges.jpg"

[[params.features]]
name = "healthy-food"
background = "/images/features/breakfast.jpg"

[[params.features]]
name = "child-care"
background = "/images/features/kids.jpg"


# Social links: add as many as you need.
# Here's a list of the most popular fa-icons:
# [fa-facebook-square, fa-twitter-square, fa-instagram, fa-google-plus-square, fa-linkedin-square, fa-tumblr-square, fa-github, fa-envelope]
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/makezurich"
    text = "@makezurich"
    icon = "fa-twitter-square"

[[params.social]]
	title = "github"
	url = "https://github.com/make-zurich"
    text = "github.com/make-zurich"
    icon = "fa-github"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/events/2615070568610092"
    text = "Open Network Infrastructure Association"
    icon = "fa-facebook-square"

[[params.social]]
	title = "instagram"
	url = "https://instagram.com/makezurich"
    text = "@makezurich"
    icon = "fa-instagram"

[[params.social]]
	title = "email"
	url = "mailto:info@makezurich.ch"
    text = "info@makezurich.ch"
    icon = "fa-envelope"

# SEO Options: all verification codes are optional
[params.seo.verification]
    google = ""
    bing = ""
    alexa = ""
    yandex = ""

[languages]
[languages.en]
weight = 1
languageName = "English"

[[languages.en.menu.main]]
    name = "Schedule"
    url = "/#schedule"
    weight = 2

[[languages.en.menu.main]]
    name = "Venue"
    url = "/#venue"
    weight = 3

[[languages.en.menu.main]]
    name = "Challenges"
    url = "/#challenges"
    weight = 4

# [[languages.en.menu.highlighted]]
#     # DURING
#     name = "Projects"
#     url = "https://now.makezurich.ch/event/4"
#     weight = 4
#     pre = "btn-black"
#     post = "fa-tasks"

# PRIMARY BUTTON LINK
# Change links according to event stage:
# Before event=Register
# During event=Getting Started
# After=Projects
[[languages.en.menu.highlighted]]
    # BEFORE
    # name = "Register"
    # url = "/register"
    # DURING
    # name = "Getting started"
    # url = "/start"

    # AFTER
    name = "Projects"
    url = "https://now.makezurich.ch/event/4"
    weight = 5
    pre = "btn-black"
    post = "fa-sign-in"

# PRIMARY BUTTON LINK (Hero)
# Same as the one above
[[languages.en.menu.hero]]
    # BEFORE
    # name = "Register"
    # url = "/register"
    # DURING
    # name = "Getting started"
    # url = "/start"
    # AFTER
    name = "Projects"
    url = "https://now.makezurich.ch/event/4"
    pre = "event-primary-color"
    post = "fa-sign-in"

[languages.de]
weight = 2
languageName = "Deutsch"

[[languages.de.menu.main]]
    name = "Zeitplan"
    url = "/#schedule"
    weight = 2

[[languages.de.menu.main]]
    name = "Venue"
    url = "/#venue"
    weight = 3

[[languages.de.menu.main]]
    name = "Challenges"
    url = "/#challenges"
    weight = 4

# [[languages.de.menu.highlighted]]
#     # DURING
#     name = "Projekte"
#     url = "https://now.makezurich.ch/event/4"
#     weight = 4
#     pre = "btn-black"
#     post = "fa-tasks"

# PRIMARY BUTTON LINK
# Change links according to event stage:
# Before event=Register
# During event=Getting Started
# After=Projects
[[languages.de.menu.highlighted]]
    # BEFORE
    # name = "Anmelden"
    # url = "/register"
    # DURING
    # name = "Getting started"
    # url = "/de/start"
    # AFTER
    name = "Projekte"
    url = "https://now.makezurich.ch/event/4"
    weight = 5
    pre = "btn-black"
    post = "fa-sign-in"

# PRIMARY BUTTON LINK (Hero)
# Same as the one above
[[languages.de.menu.hero]]
    # BEFORE
    # name = "Anmelden"
    # url = "/register"
    # DURING
    # name = "Getting started"
    # url = "/de/start"
    # AFTER
    name = "Projekte"
    url = "https://now.makezurich.ch/event/4"
    pre = "event-primary-color"
    post = "fa-sign-in"

# Hugo's Markdown rendering engine options
[blackfriday]
hrefTargetBlank = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
